#!/bin/bash -ex

HOSTNAME=nzbapp
USERNAME=nzb
GROUPNAME=nzb

# set hostname
echo "$HOSTNAME" > /etc/hostname
sed -i "s|127.0.1.1 \(.*\)|127.0.1.1 $HOSTNAME|" /etc/hosts

# create the nzb userid (which all the nzb daemons run as)
groupadd $GROUPNAME
useradd -c "NZB App userid" -d /home/$USERNAME -g $GROUPNAME -m -s /bin/bash "$USERNAME"
chown -R $USERNAME:$GROUPNAME /home/$USERNAME

# Change ownership of log folders
chown -R $USERNAME:$GROUPNAME /var/log/sabnzbdplus
chown -R $USERNAME:$GROUPNAME /var/log/sickbeard
chown -R $USERNAME:$GROUPNAME /var/log/couchpotato #TODO: Configure couchpotato logs when available
chown -R $USERNAME:$GROUPNAME /var/log/headphones 

# add the python installation tools and sudo
apt-get update
DEBIAN_FRONTEND=noninteractive apt-get -y \
    -o DPkg::Options::=--force-confdef \
    -o DPkg::Options::=--force-confold \
    install python-software-properties sudo

####################################################
# INSTALL SABNZBD
####################################################
# add the repo 
add-apt-repository ppa:jcfp/ppa
apt-get update
# install SABnzbd
DEBIAN_FRONTEND=noninteractive apt-get -y \
    -o DPkg::Options::=--force-confdef \
    -o DPkg::Options::=--force-confold \
    install sabnzbdplus sabnzbdplus-theme-mobile python-pyopenssl unrar par2 php5-curl 

# set it to start automatically
update-rc.d sabnzbdplus defaults

# move in the config file
mkdir /home/$USERNAME/.sabnzbd
chown -R $USERNAME:$GROUPNAME /home/$USERNAME/.sabnzbd
mv /home/$USERNAME/config/.sabnzbd/sabnzbd.ini /home/$USERNAME/.sabnzbd/sabnzbd.ini


####################################################
# INSTALL SICKBEARD
####################################################
cd /home/$USERNAME
git clone git://github.com/midgetspy/Sick-Beard.git .sickbeard
chown -R $USERNAME:$GROUPNAME .sickbeard

# set it to start automatically
update-rc.d sickbeard defaults

mv /home/$USERNAME/config/.sickbeard/config.ini /home/$USERNAME/.sickbeard
mv /home/$USERNAME/config/.sickbeard/autoProcessTV/autoProcessTV.cfg /home/$USERNAME/.sickbeard/autoProcessTV/autoProcessTV.cfg

####################################################
# INSTALL COUCHPOTATO 
####################################################
cd /home/$USERNAME
git clone git://github.com/RuudBurger/CouchPotato.git .couchpotato
chown -R $USERNAME:$GROUPNAME .couchpotato

# set it to start automatically
update-rc.d couchpotato defaults

mv /home/$USERNAME/config/.couchpotato/config.ini /home/$USERNAME/.couchpotato

####################################################
# INSTALL  HEADPHONES
####################################################
cd /home/$USERNAME
git clone git://github.com/rembo10/headphones.git .headphones
chown -R $USERNAME:$GROUPNAME .headphones

# set it to start automatically
cp .headphones/init.ubuntu /etc/init.d/headphones
chmod +x /etc/init.d/headphones
sed -i "s|APP_PATH=\(.*\)|APP_PATH=/home/$USERNAME/.headphones|" /etc/init.d/headphones
update-rc.d headphones defaults

mv /home/$USERNAME/config/.headphones/config.ini /home/$USERNAME/.headphones


####################################################
# INSTALL MARASCHINO
####################################################
# install dependencies
DEBIAN_FRONTEND=noninteractive apt-get -y \
    -o DPkg::Options::=--force-confdef \
    -o DPkg::Options::=--force-confold \
    install \
    sqlite3


cd /home/$USERNAME
git clone https://github.com/mrkipling/maraschino.git .maraschino
cp .maraschino/settings_example.py .maraschino/settings.py
sed -i "s|DATABASE =\(.*\)|DATABASE='/home/$USERNAME/.maraschino/maraschino.db'|" .maraschino/settings.py
# set it to start automatically
cp .maraschino/initd /etc/init.d/maraschino
chmod +x /etc/init.d/maraschino
mv /home/nzb/maraschino.db /home/nzb/.maraschino
sed -i "s|APP_PATH=\(.*\)|APP_PATH=/home/$USERNAME/.maraschino|" /etc/init.d/maraschino
sed -i "s|RUN_AS=\(.*\)|RUN_AS=$USERNAME|" /etc/init.d/maraschino
update-rc.d maraschino defaults
chown -R $USERNAME:$GROUPNAME .maraschino

cp /home/$USERNAME/config/lighttpd/lighttpd.conf /etc/lighttpd


chown -R $USERNAME:$GROUPNAME /home/$USERNAME

####################################################
# Final tasks
####################################################
# since we're storing files in /srv/storage,
# make it world writable
chmod -R 777 /srv/storage

# setup iptables to allow traffic on our ports
# iptables -A INPUT -i eth0 -p tcp -m multiport --dports 8080,8081,8085 -m state --state NEW,ESTABLISHED -j ACCEPT

# Create the service file
echo "Maraschino:     http://nzbapp" > /etc/confconsole/services.txt
echo "File Manager:   http://nzbapp/extplorer" >> /etc/confconsole/services.txt
echo "Web Shell:      http://nzbapp:12320" >> /etc/confconsole/services.txt
echo "Webmin:         http://nzbapp:12321" >> /etc/confconsole/services.txt
echo "SMB/CIFS:       nzbapp (ports 139/445)" >> /etc/confconsole/services.txt
echo " " >> /etc/confconsole/services.txt
echo "IP Address:     \$ipaddr " >> /etc/confconsole/services.txt

####################################################
# done!
####################################################
exit




