#!/bin/bash -e

HOSTNAME=nzbapp
USERNAME=nzb
GROUPNAME=nzb

# get the turnkey version
DEBVER=`cat /etc/debian_version`

# set hostname
echo "$HOSTNAME" > /etc/hostname
sed -i "s|127.0.1.1 \(.*\)|127.0.1.1 $HOSTNAME|" /etc/hosts

# create the nzb userid (which all the nzb daemons run as)
groupadd $GROUPNAME
useradd -c "NZB App userid" -d /home/$USERNAME -g $GROUPNAME -m -s /bin/bash "$USERNAME"

chown -R $USERNAME:$GROUPNAME /home/$USERNAME

# Change ownership of log folders
chown -R $USERNAME:$GROUPNAME /var/log/sabnzbdplus
chown -R $USERNAME:$GROUPNAME /var/log/sickbeard
chown -R $USERNAME:$GROUPNAME /var/log/couchpotato 
chown -R $USERNAME:$GROUPNAME /var/log/headphones 

# add the python installation tools and sudo
apt-get update
DEBIAN_FRONTEND=noninteractive apt-get -y \
    -o DPkg::Options::=--force-confdef \
    -o DPkg::Options::=--force-confold \
    install python-software-properties sudo 

# add our user to the sudoers list
echo "${USERNAME}    ALL=(ALL:ALL) ALL" > /etc/sudoers.d/${USERNAME}

####################################################
# INSTALL SABNZBD
####################################################

echo "deb http://ppa.launchpad.net/jcfp/ppa/ubuntu lucid main" | tee -a /etc/apt/sources.list
apt-key adv --keyserver hkp://pool.sks-keyservers.net:11371 --recv-keys 0x98703123E0F52B2BE16D586EF13930B14BB9F05F
apt-get update

PACKAGES="sabnzbdplus sabnzbdplus-theme-mobile python-pyopenssl unrar par2 php5-curl"
if [[ "$DEBVER" == *7.* ]]; then
   echo "Installing packages for Debian ver 7.x"
   PACKAGES="sabnzbdplus sabnzbdplus-theme-mobile python-openssl unrar par2 php5-curl"
fi
if [[ "$DEBVER" == *8.* ]]; then
   echo "Installing packages for Debian ver 8.x"
   PACKAGES="sabnzbdplus sabnzbdplus-theme-mobile python-openssl unrar par2 php5-curl"
fi

echo "Packages for ${DEBVER}: ${PACKAGES}"

# install SABnzbd
DEBIAN_FRONTEND=noninteractive apt-get -y \
    -o DPkg::Options::=--force-confdef \
    -o DPkg::Options::=--force-confold \
    install ${PACKAGES} 

# set it to start automatically
update-rc.d sabnzbdplus defaults



####################################################
# INSTALL SICKBEARD
####################################################
cd /home/$USERNAME
# oddly enough, sometimes the .sickbeard directory does not get cleaned up
if [ -d .sickbeard ]; then
  rm -rf .sickbeard
fi
git clone git://github.com/midgetspy/Sick-Beard.git .sickbeard

# set it to start automatically
update-rc.d sickbeard defaults

mv /home/$USERNAME/config/.sickbeard/config.ini /home/$USERNAME/.sickbeard
mv /home/$USERNAME/config/.sickbeard/autoProcessTV/autoProcessTV.cfg /home/$USERNAME/.sickbeard/autoProcessTV/autoProcessTV.cfg

####################################################
# INSTALL COUCHPOTATO SERVER 
####################################################
cd /home/$USERNAME
git clone git://github.com/RuudBurger/CouchPotatoServer.git .couchpotato

# set it to start automatically
update-rc.d couchpotato defaults

mv /home/$USERNAME/config/.couchpotato/settings.conf /home/$USERNAME/.couchpotato

####################################################
# INSTALL  HEADPHONES
####################################################
cd /home/$USERNAME
git clone git://github.com/rembo10/headphones.git .headphones

# set it to start automatically
cp .headphones/init-scripts/init.ubuntu /etc/init.d/headphones
chmod +x /etc/init.d/headphones
sed -i "s|APP_PATH=\(.*\)|APP_PATH=/home/$USERNAME/.headphones|" /etc/init.d/headphones
update-rc.d headphones defaults

mv /home/$USERNAME/config/.headphones/config.ini /home/$USERNAME/.headphones


####################################################
# INSTALL HTPC.IO
####################################################
# install dependencies
DEBIAN_FRONTEND=noninteractive apt-get -y \
    -o DPkg::Options::=--force-confdef \
    -o DPkg::Options::=--force-confold \
    install \
    sqlite3 libjpeg62-turbo-dev libpng-dev libfreetype6 libfreetype6-dev zlib1g-dev \
    python-pip python2.7-dev build-essential python-imaging cifs-utils

sudo ln -s /usr/lib/x86_64-linux-gnu/libz.so /usr/lib/libz.so
sudo ln -s /usr/lib/x86_64-linux-gnu/libjpeg.so /usr/lib/libjpeg.so
sudo ln -s /usr/lib/x86_64-linux-gnu/libfreetype.so /usr/lib/libfreetype.so

# pip install PIL

cd /home/$USERNAME
git clone https://github.com/styxit/HTPC-Manager .htpc.io 
cp .htpc.io/initd /etc/init.d/htpc.io
chmod +x /etc/init.d/htpc.io
sed -i "s|APP_PATH=\(.*\)|APP_PATH=/home/$USERNAME/.htpc.io|" /etc/init.d/htpc.io
sed -i "s|RUN_AS=\(.*\)|RUN_AS=$USERNAME|" /etc/init.d/htpc.io
sed -i "s|PID_FILE=\(.*\)|PID_FILE=/tmp/htpcmanager.pid|" /etc/init.d/htpc.io
update-rc.d htpc.io defaults


cp /home/$USERNAME/config/lighttpd/lighttpd.conf /etc/lighttpd
chown -R $USERNAME:$GROUPNAME /home/$USERNAME

####################################################
# Final tasks
####################################################
# since we're storing files in /srv/storage,
# make it world writable
chmod -R 777 /srv/storage

# setup iptables to allow traffic on our ports
# iptables -A INPUT -i eth0 -p tcp -m multiport --dports 8080,8081,8085 -m state --state NEW,ESTABLISHED -j ACCEPT

# Create the service file
echo "HTPC:           http://\$ipaddr:7000"         > /etc/confconsole/services.txt
echo "Sabnzbd:        http://\$ipaddr:8080"        >> /etc/confconsole/services.txt
echo "CouchPotato:    http://\$ipaddr:8085"        >> /etc/confconsole/services.txt
echo "Sickbeard:      http://\$ipaddr:8081"        >> /etc/confconsole/services.txt
echo "Headphones:     http://\$ipaddr:8181"        >> /etc/confconsole/services.txt
# echo "File Manager:   http://\$ipaddr/extplorer"   >> /etc/confconsole/services.txt
echo "Web Shell:      http://\$ipaddr:12320"       >> /etc/confconsole/services.txt
echo "Webmin:         http://\$ipaddr:12321"       >> /etc/confconsole/services.txt
echo "SMB/CIFS:       nzbapp (ports 139/445)"      >> /etc/confconsole/services.txt

####################################################
# done!
####################################################
exit




