#!/bin/bash 
# copy configuration from SABnzbd to CouchPotato and SickBeard

function randompass () {
        local randompassLength
        if [ $1 ]; then
                randompassLength=$1
        else
                randompassLength=8
        fi
 
        pass=`</dev/urandom tr -dc a-f0-9 | head -c $randompassLength`
        echo $pass
}

# check to see if we've already run
if [ -f /home/nzb/SAB_APIKEY ]; then
   exit 0
fi

# Generate a random SABnzbd APIKEY and NZBKEY 
SAB_APIKEY=`randompass 32`
SAB_NZBKEY=`randompass 32`
SICK_APIKEY=`randompass 32`
COUCH_APIKEY=`randompass 32`

# replace the keys in the SABnzbd config file
service sabnzbd stop
CONFIG=/home/nzb/.sabnzbd/sabnzbd.ini
sed -i "s|SAB_APIKEY|$SAB_APIKEY|" $CONFIG
sed -i "s|SAB_NZBKEY|$SAB_NZBKEY|" $CONFIG
service sabnzbd start

# replace the keys in the CouchPotato config file
service couchpotato stop
CONFIG=/home/nzb/.couchpotato/settings.conf
sed -i "s|SAB_APIKEY|$SAB_APIKEY|" $CONFIG
sed -i "s|SAB_NZBKEY|$SAB_NZBKEY|" $CONFIG
sed -i "s|COUCH_APIKEY|$COUCH_APIKEY|" $CONFIG
/etc/init.d/couchpotato start

# replace the keys in the SickBeard config file
service sickbeard stop
CONFIG=/home/nzb/.sickbeard/config.ini
sed -i "s|SAB_APIKEY|$SAB_APIKEY|" $CONFIG
sed -i "s|SAB_NZBKEY|$SAB_NZBKEY|" $CONFIG
sed -i "s|SICK_APIKEY|$SICK_APIKEY|" $CONFIG
service sickbeard start

# replace the keys in the Headphones config file
service headphones stop
CONFIG=/home/nzb/.headphones/config.ini
sed -i "s|SAB_APIKEY|$SAB_APIKEY|" $CONFIG
sed -i "s|SAB_NZBKEY|$SAB_NZBKEY|" $CONFIG
service headphones start

# replace the HOSTNAME in the lighthttpd conf file 
HOSTNAME=`hostname`
CONFIG=/etc/lighttpd/lighttpd.conf
sed -i "s|NZBAPP_HOSTNAME|$HOSTNAME|" $CONFIG

echo $SAB_APIKEY > /home/nzb/SAB_APIKEY
echo $SAB_NZBKEY > /home/nzb/SAB_NZBKEY
echo $SICK_APIKEY > /home/nzb/SICK_APIKEY

# put all the entries into the htpc db as well
service htpc.io stop
CONFIG=/home/nzb/init_htpc.io.sql
cd /home/nzb/.htpc.io
if [ ! -d userdata ]; then
   mkdir userdata
fi 
mv /home/nzb/database.db userdata/
chown -R nzb:nzb /home/nzb

sed -i "s|APP_PORT|7000|g" $CONFIG
sed -i "s|SAB_APIKEY|$SAB_APIKEY|g" $CONFIG
sed -i "s|SAB_NZBKEY|$SAB_NZBKEY|g" $CONFIG
sed -i "s|SICK_APIKEY|$SICK_APIKEY|g" $CONFIG
sed -i "s|COUCH_APIKEY|$COUCH_APIKEY|" $CONFIG
sed -i "s|NZBAPP_HOSTNAME|$HOSTNAME|g" $CONFIG
sqlite3 userdata/database.db < /home/nzb/init_htpc.io.sql

service htpc.io start

# restart the lighthttpd daemon
/etc/init.d/lighttpd restart

