#!/bin/bash -e
# copy configuration from SABnzbd to CouchPotato and SickBeard

function randompass () {
        local randompassLength
        if [ $1 ]; then
                randompassLength=$1
        else
                randompassLength=8
        fi
 
        pass=</dev/urandom tr -dc a-f0-9 | head -c $randompassLength
        echo $pass
}

# check to see if we've already run
if [ -f /home/nzb/SAB_APIKEY ]; then
   exit 0
fi

# Generate a random SABnzbd APIKEY and NZBKEY 
SAB_APIKEY=`randompass 32`
SAB_NZBKEY=`randompass 32`
SICK_APIKEY=`randompass 32`

# replace the keys in the SABnzbd config file
CONFIG=/home/nzb/.sabnzbd/sabnzbd.ini
sed -i "s|SAB_APIKEY|$SAB_APIKEY|" $CONFIG
sed -i "s|SAB_NZBKEY|$SAB_NZBKEY|" $CONFIG

# replace the keys in the CouchPotato config file
CONFIG=/home/nzb/.couchpotato/config.ini
sed -i "s|SAB_APIKEY|$SAB_APIKEY|" $CONFIG
sed -i "s|SAB_NZBKEY|$SAB_NZBKEY|" $CONFIG

# replace the keys in the SickBeard config file
CONFIG=/home/nzb/.sickbeard/config.ini
sed -i "s|SAB_APIKEY|$SAB_APIKEY|" $CONFIG
sed -i "s|SAB_NZBKEY|$SAB_NZBKEY|" $CONFIG
sed -i "s|SICK_APIKEY|$SAB_NZBKEY|" $CONFIG

# replace the keys in the Headphones config file
CONFIG=/home/nzb/.headphones/config.ini
sed -i "s|SAB_APIKEY|$SAB_APIKEY|" $CONFIG
sed -i "s|SAB_NZBKEY|$SAB_NZBKEY|" $CONFIG

# replace the HOSTNAME in the lighthttpd conf file 
HOSTNAME=`hostname`
CONFIG=/etc/lighttpd/lighttpd.conf
sed -i "s|NZBAPP_HOSTNAME|$HOSTNAME|" $CONFIG

echo $SAB_APIKEY > /home/nzb/SAB_APIKEY
echo $SAB_NZBKEY > /home/nzb/SAB_NZBKEY
echo $SICK_APIKEY > /home/nzb/SICK_APIKEY

# put all the entries into the maraschone db as well
CONFIG=/home/nzb/init_maraschino.sql
cd /home/nzb/.maraschino
sed -i "s|SAB_APIKEY|$SAB_APIKEY|g" $CONFIG
sed -i "s|SAB_NZBKEY|$SAB_NZBKEY|g" $CONFIG
sed -i "s|SICK_APIKEY|$SICK_APIKEY|g" $CONFIG
sed -i "s|NZBAPP_HOSTNAME|$HOSTNAME|g" $CONFIG
sqlite3 maraschino.db < /home/nzb/init_maraschino.sql

# restart the lighthttpd daemon
/etc/init.d/lighttpd restart


