#!/bin/bash -e
# copy configuration from SABnzbd to CouchPotato and SickBeard

function randompass () {
        local randompassLength
        if [ $1 ]; then
                randompassLength=$1
        else
                randompassLength=8
        fi
 
        pass=</dev/urandom tr -dc A-Fa-f0-9 | head -c $randompassLength
        echo $pass
}

# Generate a random SABnzbd APIKEY and NZBKEY 
SAB_APIKEY=`randompass 32`
SAB_NZBKEY=`randompass 32`

# replace the keys in the SABnzbd config file
CONFIG=/home/nzb/.sabnzbd/sabnzbd.ini
sed -i "s|SAB_APIKEY|$SAB_APIKEY|" $CONFIG
sed -i "s|SAB_NZBKEY|$SAB_NZBKEY|" $CONFIG

# replace the keys in the CouchPotato config file
CONFIG=/home/nzb/.couchpotato/config.ini
sed -i "s|SAB_APIKEY|$SAB_APIKEY|" $CONFIG
sed -i "s|SAB_NZBKEY|$SAB_NZBKEY|" $CONFIG

# replace the keys in the SickBeard config file
CONFIG=/home/nzb/.sickbeard/config.ini
sed -i "s|SAB_APIKEY|$SAB_APIKEY|" $CONFIG
sed -i "s|SAB_NZBKEY|$SAB_NZBKEY|" $CONFIG

echo $SAB_APIKEY > /home/nzb/SAB_APIKEY

echo $SAB_NZBKEY > /home/nzb/SAB_NZBKEY



